import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { prisma } from "../src/db";
import { Todo } from "@prisma/client";
import Link from "next/link";

export const getServerSideProps: GetServerSideProps = async () => {
  const todos = await prisma.todo.findMany();

  return {
    props: { todos },
  };
};

interface HomeProps {
  todos: Todo[];
}

const Home: NextPage<HomeProps> = ({ todos }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>List of ToDos</h1>

        <ul>
          {todos.map((todo) => (
            <li key={todo.id}>
              ToDo with id: <pre style={{ display: "inline" }}>{todo.id}</pre>
            </li>
          ))}
        </ul>

        <Link href="/new">Create ToDo</Link>
        <Link href="/remove">Remove all ToDos</Link>
      </main>
    </div>
  );
};

export default Home;
